---
- name: Create IDM CA config-map
  k8s:
    state: present
    definition: 
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: ldap-secret
        namespace: openshift-config
      data:
      


- name: Create IDM bind secret
  k8s:
    state: present
    definition:

- name: Create OAuth object for IDM
  k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
        - name: ldapidp 
          mappingMethod: claim 
          type: LDAP
          ldap:
            attributes:
              id: 
              - dn 
              email: 
              - mail
              name: 
              - cn
              preferredUsername: 
              - uid
            bindDN: "uid=admin,cn=users,cn=accounts,dc=example,dc=com" 
            bindPassword: 
              name: ldap-secret
            ca: 
              name: ca-config-map
            insecure: false 
            url: "ldap://idm.example.com./cn=accounts,dc=example,dc=com?uid"
